### ISSUE TITLE
Fix syntax errors in app.py

### ISSUE THREAD

**Issue by varchanaiyer** [Harmandeep04Kaur/IntelProject#1]
![image](https://github.com/user-attachments/assets/14f7db21-6973-4785-b331-81fdedb8a218)

Debug and resolve the syntax errors in the app.py file to ensure proper functionality of the application. Pay special attention to line 184 and surrounding code

**Comment by Harmandeep04Kaur** [comment]
Everything solved from our side...kindly activate virtual environment (**.venv)** to avoid any packages **issue.** 


![code](https://github.com/user-attachments/assets/95103822-2904-4fe6-a350-4c3d5a7a1cd0)

https://github.com/user-attachments/assets/b3137024-7c32-4e1b-9911-e87ef8f970e3
